// types of post
export const GET_LIST_POST_REQUEST = 'GET_LIST_POST_REQUEST';
export const GET_LIST_POST_SUCCESS = 'GET_LIST_POST_SUCCESS';
export const GET_LIST_POST_FAILURE = 'GET_LIST_POST_FAILURE';