version: "3.8"
services:
  frontend:
    image: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - my-app
  backend:
    image: backend
    ports:
      - "8080:8080"
    networks:
      - my-app
networks: 
  my-app:
    driver: bridge
